### ISSUE TITLE
Not able to run the pipeline code

### ISSUE THREAD

**Issue by omkar820** [VirginiaSabando/MTL_DNN_Ames#2]
I am trying to run the pipeline. I copied all the code into my system and tried to run the following code as it is by just changing the data path and model checkpoint path. However It goes and works well till the model fit code. It is giving me error of Expected binary or unicode string, got 0.364671287. Please let me know if you have any suggestion or solution for the same. 

Here is the traceback of the same:
`
2024-08-21 12:56:33.892873: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-21 12:56:33.909870: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-21 12:56:33.915058: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-21 12:56:33.927440: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-21 12:56:34.772388: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1724225205.395532 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.427080 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.427355 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.443538 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.443811 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.444028 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.520659 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.520897 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1724225205.521083 4176575 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-08-21 12:56:45.521221: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 32871 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:06:00.0, compute capability: 8.6
/home/omkarn/miniconda3/envs/yashasvi_54/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py:2311: UserWarning: Seed 3 from outer graph might be getting used by function Dataset_map_permutation, if the random op has not been provided any seed. Explicitly set the seed in the function if this is not the intended behavior.
  return map_op._map_v2(
Traceback (most recent call last):
  File "/mnt/prj008/Omkar/Bitbucket/Ames Mutagenicity/Paper-Approach/MTL_DNN_Ames-main/MTL_CFV.py", line 296, in <module>
    trained_model = run_MTL(x_train, x_test, y_train, y_test, lb, spec_lay, arq, w, idx)
  File "/mnt/prj008/Omkar/Bitbucket/Ames Mutagenicity/Paper-Approach/MTL_DNN_Ames-main/MTL_CFV.py", line 267, in run_MTL
    learning_data = model.fit(x=x_train,
  File "/home/omkarn/miniconda3/envs/yashasvi_54/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/omkarn/miniconda3/envs/yashasvi_54/lib/python3.9/site-packages/tensorflow/python/util/compat.py", line 81, in as_bytes
    raise TypeError('Expected binary or unicode string, got %r' %
TypeError: Expected binary or unicode string, got 0.364671287

`

**Comment by omkar820** [comment]
Tried with tensorflow version 2.10.1 and it works. Thanks
